# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: dispatch

concurrency:
  group: current-group
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'User number'
        required: true
      user_count:
        description: 'Number of users'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Run ${{ github.event.inputs.user}}
      env:
        BOT_KEY: ${{ secrets.BOT_KEY }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        KEY: ${{ secrets.KEY }}
        PPAT: ${{ secrets.PPAT }}
        P1: ${{ secrets.P1 }}
        S1: ${{ secrets.S1 }}
        C1: ${{ secrets.C1 }}
        P2: ${{ secrets.P2 }}
        S2: ${{ secrets.S2 }}
        C2: ${{ secrets.C2 }}
        P3: ${{ secrets.P3 }}
        S3: ${{ secrets.S3 }}
        C3: ${{ secrets.C3 }}
        P4: ${{ secrets.P4 }}
        S4: ${{ secrets.S4 }}
        C4: ${{ secrets.C4 }}
      run: ./pusher.sh ${{ github.event.inputs.user }} ${{ github.event.inputs.user_count }}
