# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: dispatch

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'User number'
        required: true
      user_count:
        description: 'Number of users'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Run ${{ github.event.inputs.user}}
      env:
        KEY: ${{ secrets.KEY }}
        PPAT: ${{ secrets.PPAT }}
        P1: ${{ secrets.P1 }}
        S1: ${{ secrets.S1 }}
        C1: ${{ secrets.C1 }}
        P2: ${{ secrets.P1 }}
        S2: ${{ secrets.S1 }}
        C2: ${{ secrets.C1 }}
        P3: ${{ secrets.P1 }}
        S3: ${{ secrets.S1 }}
        C3: ${{ secrets.C1 }}
        P4: ${{ secrets.P1 }}
        S4: ${{ secrets.S1 }}
        C4: ${{ secrets.C1 }}
      run: ./pusher.sh ${{ github.event.inputs.user }} ${{ github.event.inputs.user_count }}
